use crate::models::{CipherSuiteInfo, Protocol, SecurityRating};

pub const ALL_CIPHERS: &[CipherSuiteInfo] = &[
    // ==========================================
    // TLS 1.3 Cipher Suites (RFC 8446)
    // ==========================================
    CipherSuiteInfo {
        id: 0x1301,
        iana_name: "TLS_AES_128_GCM_SHA256",
        openssl_name: "AEAD-AES128-GCM-SHA256",
        protocol_min: Protocol::Tls13,
        key_exchange: "ECDHE/DHE",
        encryption: "AES-128-GCM",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0x1302,
        iana_name: "TLS_AES_256_GCM_SHA384",
        openssl_name: "AEAD-AES256-GCM-SHA384",
        protocol_min: Protocol::Tls13,
        key_exchange: "ECDHE/DHE",
        encryption: "AES-256-GCM",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0x1303,
        iana_name: "TLS_CHACHA20_POLY1305_SHA256",
        openssl_name: "AEAD-CHACHA20-POLY1305-SHA256",
        protocol_min: Protocol::Tls13,
        key_exchange: "ECDHE/DHE",
        encryption: "CHACHA20-POLY1305",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0x1304,
        iana_name: "TLS_AES_128_CCM_SHA256",
        openssl_name: "AEAD-AES128-CCM-SHA256",
        protocol_min: Protocol::Tls13,
        key_exchange: "ECDHE/DHE",
        encryption: "AES-128-CCM",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Secure,
    },
    CipherSuiteInfo {
        id: 0x1305,
        iana_name: "TLS_AES_128_CCM_8_SHA256",
        openssl_name: "AEAD-AES128-CCM8-SHA256",
        protocol_min: Protocol::Tls13,
        key_exchange: "ECDHE/DHE",
        encryption: "AES-128-CCM-8",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Secure,
    },

    // ==========================================
    // TLS 1.2 Modern AEAD + PFS (Secure/Recommended)
    // ==========================================
    CipherSuiteInfo {
        id: 0xc02b,
        iana_name: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        openssl_name: "ECDHE-ECDSA-AES128-GCM-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "AES-128-GCM",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0xc02c,
        iana_name: "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        openssl_name: "ECDHE-ECDSA-AES256-GCM-SHA384",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "AES-256-GCM",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0xc02f,
        iana_name: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        openssl_name: "ECDHE-RSA-AES128-GCM-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "AES-128-GCM",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0xc030,
        iana_name: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        openssl_name: "ECDHE-RSA-AES256-GCM-SHA384",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "AES-256-GCM",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0xcca9,
        iana_name: "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
        openssl_name: "ECDHE-ECDSA-CHACHA20-POLY1305",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "CHACHA20-POLY1305",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0xcca8,
        iana_name: "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
        openssl_name: "ECDHE-RSA-CHACHA20-POLY1305",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "CHACHA20-POLY1305",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Recommended,
    },
    CipherSuiteInfo {
        id: 0xccaa,
        iana_name: "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
        openssl_name: "DHE-RSA-CHACHA20-POLY1305",
        protocol_min: Protocol::Tls12,
        key_exchange: "DH",
        encryption: "CHACHA20-POLY1305",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Secure,
    },
    CipherSuiteInfo {
        id: 0x009e,
        iana_name: "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
        openssl_name: "DHE-RSA-AES128-GCM-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "DH",
        encryption: "AES-128-GCM",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Secure,
    },
    CipherSuiteInfo {
        id: 0x009f,
        iana_name: "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
        openssl_name: "DHE-RSA-AES256-GCM-SHA384",
        protocol_min: Protocol::Tls12,
        key_exchange: "DH",
        encryption: "AES-256-GCM",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: true,
        is_aead: true,
        is_obsolete: false,
        rating: SecurityRating::Secure,
    },

    // ==========================================
    // TLS 1.2 CBC Mode Ciphers (Deprecated / Weak - Lucky13 / Padding Oracle)
    // ==========================================
    CipherSuiteInfo {
        id: 0xc027,
        iana_name: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
        openssl_name: "ECDHE-RSA-AES128-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA256",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0xc028,
        iana_name: "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
        openssl_name: "ECDHE-RSA-AES256-SHA384",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA384",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0xc023,
        iana_name: "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
        openssl_name: "ECDHE-ECDSA-AES128-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA256",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0xc024,
        iana_name: "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
        openssl_name: "ECDHE-ECDSA-AES256-SHA384",
        protocol_min: Protocol::Tls12,
        key_exchange: "ECDH",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA384",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0x0067,
        iana_name: "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256",
        openssl_name: "DHE-RSA-AES128-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "DH",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA256",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0x006b,
        iana_name: "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256",
        openssl_name: "DHE-RSA-AES256-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "DH",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA256",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },

    // ==========================================
    // TLS 1.0 / 1.1 / 1.2 SHA-1 Legacy Ciphers
    // ==========================================
    CipherSuiteInfo {
        id: 0xc013,
        iana_name: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
        openssl_name: "ECDHE-RSA-AES128-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0xc014,
        iana_name: "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
        openssl_name: "ECDHE-RSA-AES256-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0xc009,
        iana_name: "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
        openssl_name: "ECDHE-ECDSA-AES128-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0xc00a,
        iana_name: "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
        openssl_name: "ECDHE-ECDSA-AES256-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0x0033,
        iana_name: "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
        openssl_name: "DHE-RSA-AES128-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "DH",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0x0039,
        iana_name: "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
        openssl_name: "DHE-RSA-AES256-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "DH",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },

    // ==========================================
    // Static RSA Key Exchange (No Forward Secrecy)
    // ==========================================
    CipherSuiteInfo {
        id: 0x009c,
        iana_name: "TLS_RSA_WITH_AES_128_GCM_SHA256",
        openssl_name: "AES128-GCM-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "RSA",
        encryption: "AES-128-GCM",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: false,
        is_aead: true,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0x009d,
        iana_name: "TLS_RSA_WITH_AES_256_GCM_SHA384",
        openssl_name: "AES256-GCM-SHA384",
        protocol_min: Protocol::Tls12,
        key_exchange: "RSA",
        encryption: "AES-256-GCM",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: false,
        is_aead: true,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0x003c,
        iana_name: "TLS_RSA_WITH_AES_128_CBC_SHA256",
        openssl_name: "AES128-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "RSA",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA256",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0x003d,
        iana_name: "TLS_RSA_WITH_AES_256_CBC_SHA256",
        openssl_name: "AES256-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "RSA",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA256",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0x002f,
        iana_name: "TLS_RSA_WITH_AES_128_CBC_SHA",
        openssl_name: "AES128-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "RSA",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0x0035,
        iana_name: "TLS_RSA_WITH_AES_256_CBC_SHA",
        openssl_name: "AES256-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "RSA",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },

    // ==========================================
    // Insecure 3DES Ciphers (Sweet32 CVE-2016-2183)
    // ==========================================
    CipherSuiteInfo {
        id: 0x000a,
        iana_name: "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
        openssl_name: "DES-CBC3-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA",
        encryption: "3DES-EDE-CBC",
        key_bits: 112,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Insecure,
    },
    CipherSuiteInfo {
        id: 0xc012,
        iana_name: "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
        openssl_name: "ECDHE-RSA-DES-CBC3-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "3DES-EDE-CBC",
        key_bits: 112,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Insecure,
    },
    CipherSuiteInfo {
        id: 0xc008,
        iana_name: "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA",
        openssl_name: "ECDHE-ECDSA-DES-CBC3-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "3DES-EDE-CBC",
        key_bits: 112,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Insecure,
    },
    CipherSuiteInfo {
        id: 0x0016,
        iana_name: "TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA",
        openssl_name: "EDH-RSA-DES-CBC3-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "DH",
        encryption: "3DES-EDE-CBC",
        key_bits: 112,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Insecure,
    },

    // ==========================================
    // Insecure RC4 Ciphers (RFC 7465 prohibited)
    // ==========================================
    CipherSuiteInfo {
        id: 0x0005,
        iana_name: "TLS_RSA_WITH_RC4_128_SHA",
        openssl_name: "RC4-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA",
        encryption: "RC4-128",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Insecure,
    },
    CipherSuiteInfo {
        id: 0x0004,
        iana_name: "TLS_RSA_WITH_RC4_128_MD5",
        openssl_name: "RC4-MD5",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA",
        encryption: "RC4-128",
        key_bits: 128,
        mac: "MD5",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Insecure,
    },
    CipherSuiteInfo {
        id: 0xc011,
        iana_name: "TLS_ECDHE_RSA_WITH_RC4_128_SHA",
        openssl_name: "ECDHE-RSA-RC4-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "RC4-128",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Insecure,
    },
    CipherSuiteInfo {
        id: 0xc007,
        iana_name: "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA",
        openssl_name: "ECDHE-ECDSA-RC4-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "RC4-128",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Insecure,
    },

    // ==========================================
    // Insecure Single DES (56-bit key)
    // ==========================================
    CipherSuiteInfo {
        id: 0x0009,
        iana_name: "TLS_RSA_WITH_DES_CBC_SHA",
        openssl_name: "DES-CBC-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA",
        encryption: "DES-56-CBC",
        key_bits: 56,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x0015,
        iana_name: "TLS_DHE_RSA_WITH_DES_CBC_SHA",
        openssl_name: "EDH-RSA-DES-CBC-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "DH",
        encryption: "DES-56-CBC",
        key_bits: 56,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },

    // ==========================================
    // Export Ciphers (40/56-bit keys - FREAK / Logjam)
    // ==========================================
    CipherSuiteInfo {
        id: 0x0003,
        iana_name: "TLS_RSA_EXPORT_WITH_RC4_40_MD5",
        openssl_name: "EXP-RC4-MD5",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA_EXPORT",
        encryption: "RC4-40",
        key_bits: 40,
        mac: "MD5",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x0006,
        iana_name: "TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5",
        openssl_name: "EXP-RC2-CBC-MD5",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA_EXPORT",
        encryption: "RC2-40",
        key_bits: 40,
        mac: "MD5",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x0008,
        iana_name: "TLS_RSA_EXPORT_WITH_DES40_CBC_SHA",
        openssl_name: "EXP-DES-CBC-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA_EXPORT",
        encryption: "DES-40-CBC",
        key_bits: 40,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x0014,
        iana_name: "TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA",
        openssl_name: "EXP-EDH-RSA-DES-CBC-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "DH_EXPORT",
        encryption: "DES-40-CBC",
        key_bits: 40,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },

    // ==========================================
    // Anonymous Ciphers (No Authentication / MITM)
    // ==========================================
    CipherSuiteInfo {
        id: 0x0018,
        iana_name: "TLS_DH_anon_WITH_RC4_128_MD5",
        openssl_name: "ADH-RC4-MD5",
        protocol_min: Protocol::Ssl3,
        key_exchange: "None (Anon)",
        encryption: "RC4-128",
        key_bits: 128,
        mac: "MD5",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x001b,
        iana_name: "TLS_DH_anon_WITH_3DES_EDE_CBC_SHA",
        openssl_name: "ADH-DES-CBC3-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "None (Anon)",
        encryption: "3DES-EDE-CBC",
        key_bits: 112,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x0034,
        iana_name: "TLS_DH_anon_WITH_AES_128_CBC_SHA",
        openssl_name: "ADH-AES128-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "None (Anon)",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x003a,
        iana_name: "TLS_DH_anon_WITH_AES_256_CBC_SHA",
        openssl_name: "ADH-AES256-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "None (Anon)",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x00a6,
        iana_name: "TLS_DH_anon_WITH_AES_128_GCM_SHA256",
        openssl_name: "ADH-AES128-GCM-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "None (Anon)",
        encryption: "AES-128-GCM",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: false,
        is_aead: true,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x00a7,
        iana_name: "TLS_DH_anon_WITH_AES_256_GCM_SHA384",
        openssl_name: "ADH-AES256-GCM-SHA384",
        protocol_min: Protocol::Tls12,
        key_exchange: "None (Anon)",
        encryption: "AES-256-GCM",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: false,
        is_aead: true,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0xc018,
        iana_name: "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA",
        openssl_name: "AECDH-DES-CBC3-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "None (Anon)",
        encryption: "3DES-EDE-CBC",
        key_bits: 112,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0xc019,
        iana_name: "TLS_ECDH_anon_WITH_AES_128_CBC_SHA",
        openssl_name: "AECDH-AES128-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "None (Anon)",
        encryption: "AES-128-CBC",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0xc01a,
        iana_name: "TLS_ECDH_anon_WITH_AES_256_CBC_SHA",
        openssl_name: "AECDH-AES256-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "None (Anon)",
        encryption: "AES-256-CBC",
        key_bits: 256,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },

    // ==========================================
    // NULL Ciphers (No Encryption - Cleartext)
    // ==========================================
    CipherSuiteInfo {
        id: 0x0001,
        iana_name: "TLS_RSA_WITH_NULL_MD5",
        openssl_name: "NULL-MD5",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA",
        encryption: "None (Plaintext)",
        key_bits: 0,
        mac: "MD5",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x0002,
        iana_name: "TLS_RSA_WITH_NULL_SHA",
        openssl_name: "NULL-SHA",
        protocol_min: Protocol::Ssl3,
        key_exchange: "RSA",
        encryption: "None (Plaintext)",
        key_bits: 0,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0x003b,
        iana_name: "TLS_RSA_WITH_NULL_SHA256",
        openssl_name: "NULL-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "RSA",
        encryption: "None (Plaintext)",
        key_bits: 0,
        mac: "SHA256",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0xc001,
        iana_name: "TLS_ECDH_ECDSA_WITH_NULL_SHA",
        openssl_name: "ECDH-ECDSA-NULL-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "None (Plaintext)",
        key_bits: 0,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0xc006,
        iana_name: "TLS_ECDHE_ECDSA_WITH_NULL_SHA",
        openssl_name: "ECDHE-ECDSA-NULL-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "None (Plaintext)",
        key_bits: 0,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0xc00b,
        iana_name: "TLS_ECDH_RSA_WITH_NULL_SHA",
        openssl_name: "ECDH-RSA-NULL-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "None (Plaintext)",
        key_bits: 0,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },
    CipherSuiteInfo {
        id: 0xc010,
        iana_name: "TLS_ECDHE_RSA_WITH_NULL_SHA",
        openssl_name: "ECDHE-RSA-NULL-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "ECDH",
        encryption: "None (Plaintext)",
        key_bits: 0,
        mac: "SHA1",
        forward_secrecy: true,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Critical,
    },

    // ==========================================
    // Additional Ciphers (Camellia, ARIA, SEED)
    // ==========================================
    CipherSuiteInfo {
        id: 0x0041,
        iana_name: "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA",
        openssl_name: "CAMELLIA128-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "RSA",
        encryption: "CAMELLIA-128-CBC",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0x0084,
        iana_name: "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA",
        openssl_name: "CAMELLIA256-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "RSA",
        encryption: "CAMELLIA-256-CBC",
        key_bits: 256,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0x0096,
        iana_name: "TLS_RSA_WITH_SEED_CBC_SHA",
        openssl_name: "SEED-SHA",
        protocol_min: Protocol::Tls10,
        key_exchange: "RSA",
        encryption: "SEED-128-CBC",
        key_bits: 128,
        mac: "SHA1",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: true,
        rating: SecurityRating::Deprecated,
    },
    CipherSuiteInfo {
        id: 0xc07a,
        iana_name: "TLS_RSA_WITH_ARIA_128_GCM_SHA256",
        openssl_name: "ARIA128-GCM-SHA256",
        protocol_min: Protocol::Tls12,
        key_exchange: "RSA",
        encryption: "ARIA-128-GCM",
        key_bits: 128,
        mac: "AEAD",
        forward_secrecy: false,
        is_aead: true,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
    CipherSuiteInfo {
        id: 0xc07b,
        iana_name: "TLS_RSA_WITH_ARIA_256_GCM_SHA384",
        openssl_name: "ARIA256-GCM-SHA384",
        protocol_min: Protocol::Tls12,
        key_exchange: "RSA",
        encryption: "ARIA-256-GCM",
        key_bits: 256,
        mac: "AEAD",
        forward_secrecy: false,
        is_aead: true,
        is_obsolete: true,
        rating: SecurityRating::Weak,
    },
];

pub fn find_cipher(id: u16) -> Option<CipherSuiteInfo> {
    ALL_CIPHERS.iter().copied().find(|c| c.id == id)
}

pub fn unknown_cipher(id: u16) -> CipherSuiteInfo {
    CipherSuiteInfo {
        id,
        iana_name: "UNKNOWN_CIPHER",
        openssl_name: "UNKNOWN",
        protocol_min: Protocol::Tls10,
        key_exchange: "Unknown",
        encryption: "Unknown",
        key_bits: 0,
        mac: "Unknown",
        forward_secrecy: false,
        is_aead: false,
        is_obsolete: false,
        rating: SecurityRating::Weak,
    }
}
